PERSONALIZATION_MODEL = "gpt-5.4-mini"
JSON_RESPONSE_FORMAT = {"type": "json_object"}
PERSONALIZATION_REASONING_EFFORT = "low"
OPENAI_TIMEOUT_SECONDS = 30

SEARCH_QUERY_TOKEN_LIMIT = 800
PROFILE_TOKEN_LIMIT = 8000
SHOP_TOKEN_LIMIT = 2500
SPEAKER_TOKEN_LIMIT = 12000
